## This file contain
* Create Matrices
* Create Matrices with default Values
 * Zeros
 * Ones
* Seed with cpu and Gpu
* Convert Numpy to Torch , Torch to numpy
* Move Tensor Cpu to Gpu
* Tensor operation
    * Element wise add, sub, mul div
    * Resize
    * Calculate mean
    * Calculate STD

## Creating Matrices 

In [1]:
import numpy as np
import torch
import sys

In [2]:
# creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# convert to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
# convert to torch
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

## Create Matrices with Default Values

In [5]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
torch.ones((2, 2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [7]:
np.random.rand(2, 2)

array([[ 0.69270353,  0.51214336],
       [ 0.72307027,  0.68645447]])

In [8]:
torch.rand(2, 2)


 0.3980  0.8915
 0.3113  0.8738
[torch.FloatTensor of size 2x2]

## Seed for Reproducibility 

In [9]:
# seed
np.random.seed(0)
np.random.rand(2, 2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [10]:
# no seed
np.random.rand(2,2)

array([[ 0.4236548 ,  0.64589411],
       [ 0.43758721,  0.891773  ]])

In [11]:
# torch seed
torch.manual_seed(0)
torch.rand(2, 2)


 0.5488  0.5928
 0.7152  0.8443
[torch.FloatTensor of size 2x2]

In [12]:
torch.rand(2, 2)


 0.6028  0.8579
 0.5449  0.8473
[torch.FloatTensor of size 2x2]

In [13]:
# seed fo gpu
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

## Numpy to Torch Bridge 

In [14]:
np_arr = np.ones((2, 2))
print(np_arr)
type(np_arr)

[[ 1.  1.]
 [ 1.  1.]]


numpy.ndarray

In [15]:
# converting to torch
torch_tensor = torch.from_numpy(np_arr)
print(torch_tensor)
type(torch_tensor)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



torch.DoubleTensor

In [16]:
# torch to numpy
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

## Torch cpu to gpu to cpu

In [17]:
# check cuda is available
torch.cuda.is_available()

True

In [18]:
# clear all variable to clear ram 
# sys.modules[__name__].__dict__.clear()

In [19]:
# cpu
tensor_cpu = torch.ones(2, 2)

In [20]:
# Cpu to Gpu
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [21]:
tensor_cpu.cuda()
# Gpu to Cpu
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

## Tensor Operatoins

In [22]:
a = torch.ones(2, 2)
a


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [23]:
a.size()

torch.Size([2, 2])

In [24]:
# convert vactor
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

### Add

In [25]:
b = a + a
b


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [26]:
b = torch.add(a, a)
b


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [27]:
# in place addition 
print('Old B', b)

b.add_(a)
print('_'*60)
print()
print('New B', b)

Old B 
 2  2
 2  2
[torch.FloatTensor of size 2x2]

____________________________________________________________

New B 
 3  3
 3  3
[torch.FloatTensor of size 2x2]



### sub

In [28]:
a - a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [29]:
a.sub(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [30]:
a


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [31]:
a.sub_(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [32]:
a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

### mul

In [33]:
a = torch.ones(2,2)
b = torch.Tensor([[2,2],[2,2]])

In [34]:
a * b


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [35]:
print('Old')
print(a.mul(b))
print(a)
print('_'*60)
print('New')
print(a.mul_(b))
print(a)

Old

 2  2
 2  2
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]

____________________________________________________________
New

 2  2
 2  2
[torch.FloatTensor of size 2x2]


 2  2
 2  2
[torch.FloatTensor of size 2x2]



## Div

In [36]:
a = torch.ones(2,2)
b = torch.Tensor([[2,2],[2,2]])

In [37]:
a / b


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

In [38]:
torch.div(a,b)


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

In [39]:
a.div(b)


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

In [40]:
a.div_(b)


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

In [41]:
a


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

## Tensor Mean

In [42]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [43]:
a.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [44]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()

torch.Size([2, 10])

In [45]:
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

## Tensor STD

In [46]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]